<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Accueil - École</title>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <header>
        <h1>Bienvenue sur le site de l'école</h1>
        <nav>
            <a href="login.php">Connexion</a>
            <a href="about.php">À propos de l'école</a>
        </nav>
    </header>
    <main>
        <h2>Découvrez nos leçons et exercices</h2>
    </main>
    <footer>
        <p>&copy; 2024 École XYZ</p>
    </footer>
</body>
</html>







##################################################
#
# DO NOT EDIT THIS FILE
#
# Create a new .htaccess file in your htdocs
# directory (or example.com/htdocs/ directory)
# to add your own rules or override these rules.
#
##################################################


DirectoryIndex index.php index.html index.htm index2.html

ErrorDocument 403 https://errors.infinityfree.net/errors/403/
ErrorDocument 404 https://errors.infinityfree.net/errors/404/
ErrorDocument 500 https://errors.infinityfree.net/errors/500/







<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Exercice à trous</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            margin: 20px;
        }
        .sentence {
            font-size: 20px;
            margin: 20px;
        }
        .blank {
            display: inline-block;
            width: 120px;
            border-bottom: 2px solid black;
            text-align: center;
            font-weight: bold;
            cursor: pointer;
            min-height: 25px;
        }
        .choices {
            margin-top: 20px;
        }
        .choice {
            display: inline-block;
            padding: 10px;
            margin: 5px;
            background-color: lightblue;
            cursor: pointer;
            border-radius: 5px;
        }
        .choice.selected {
            background-color: deepskyblue;
        }
    </style>
</head>
<body>
    <h2>Complète la phrase :</h2>
    <p class="sentence">
        Le soleil se lève à l' <span class="blank" data-answer="est"></span> et se couche à l' <span class="blank" data-answer="ouest"></span>.
    </p>
    
    <div class="choices">
        <span class="choice">nord</span>
        <span class="choice">sud</span>
        <span class="choice">est</span>
        <span class="choice">ouest</span>
    </div>
    
    <p id="result"></p>
    
    <script>
        let selectedWord = "";
        
        document.querySelectorAll(".choice").forEach(choice => {
            choice.addEventListener("click", function() {
                document.querySelectorAll(".choice").forEach(c => c.classList.remove("selected"));
                this.classList.add("selected");
                selectedWord = this.textContent;
            });
        });
        
        document.querySelectorAll(".blank").forEach(blank => {
            blank.addEventListener("click", function() {
                if (selectedWord) {
                    this.textContent = selectedWord;
                    this.dataset.selected = selectedWord;
                }
            });
        });
        
        function checkAnswers() {
            let correct = true;
            document.querySelectorAll(".blank").forEach(blank => {
                if (blank.dataset.selected !== blank.dataset.answer) {
                    correct = false;
                }
            });
            document.getElementById("result").textContent = correct ? "Bonne réponse !" : "Mauvaise réponse, essaie encore.";
        }
    </script>
    
    <button onclick="checkAnswers()">Vérifier</button>
</body>
</html>
